### ISSUE TITLE
Test result of figure 2 is different than what gives in paper

### ISSUE THREAD

**Issue by forchain** [garyyu/go-dag#1]
Paper gives the result of Fig. 2 is (A, D, C, G, B, F, I, E, J, H, K).
Page 8, In "C. Step #2: ordering blocks"

And the go-dag test result is:
"(G).B.C.D.F.G.I.J.(V).E.H.K."

My guess of one of possible issues is that the "childrenB" in Step9 should be direct children of B rather than future set of B.

```go
		// step 9
		childrenB := make(map[string]*Block)
		futureSet(B, childrenB)
```

**Comment by garyyu** [comment]
There're some minor mistakes on current Phantom paper (I refer to version: https://eprint.iacr.org/2018/104.pdf). The Fig.2 ordering is the one I guess. Because the Fig.2 on the paper show blue set of Fig.2 is "(G).B.C.D.F.G.I.J.", it doesn't make sense the blue block's order is behind the red one, so the block 'E' must be after '(V)', not before, my 'go-dag' test result is more reasonable and should be correct.

About the step 9 'childrenB', we can't find any definition on the Phantom paper, so we have to guess and try. For me, the algorithm 2 "ordering blocks" is not very useful, as described on the paper, a production system should use Phantom + Spectre, that means, "blue selection algorithm" + "pairwise ordering". That's why I didn't put much effort on the Phantom "ordering" algorithm.

BTW, this go-dag repo is just the algorithm demo for the paper, it's not optimized and not feasible for big volume blocks. My another repo (https://github.com/garyyu/rust-dag) is the optimized one and very fast, feasible for production system.

**Comment by forchain** [comment]
I guess what the paper means is that we should obey topology ordering first than the phantom ordering.
That’s why E should be front of J in paper

**Comment by garyyu** [comment]
Thanks!  As discussion on #papers channel on https://daglabs.slack.com/, it is indeed a mis-understanding of the 'childrenB' on the paper, actually it means 'direct successors of B', not 'futureB'. Bug fixed and repo updated.
